"""create carrier tables

Revision ID: 477a6175369c
Revises: 
Create Date: 2026-06-22 15:29:12.172159+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '477a6175369c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_index('ix_carrier_company_paid_until', 'carrier_company', ['paid_until'], unique=False)
    op.create_index('ix_carrier_company_status', 'carrier_company', ['status'], unique=False)
    op.create_index('ix_carrier_company_telegram_user_id', 'carrier_company', ['telegram_user_id'], unique=False)
    op.create_table('admin_invite_token',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_telegram_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier_company.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('carrier_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('payload_kg', sa.Integer(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('has_tail_lift', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('has_crane', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('has_mobile_lift', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('mobile_lift_max_floor', sa.Integer(), nullable=True),
    sa.Column('mobile_lift_max_weight_kg', sa.Integer(), nullable=True),
    sa.Column('crane_max_weight_kg', sa.Integer(), nullable=True),
    sa.Column('crane_reach_meters', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carrier_vehicle_carrier_id', 'carrier_vehicle', ['carrier_id'], unique=False)
    op.create_index('ix_carrier_vehicle_is_active', 'carrier_vehicle', ['is_active'], unique=False)
    op.create_index('ix_carrier_vehicle_vehicle_type', 'carrier_vehicle', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carrier_vehicle_vehicle_type', table_name='carrier_vehicle')
    op.drop_index('ix_carrier_vehicle_is_active', table_name='carrier_vehicle')
    op.drop_index('ix_carrier_vehicle_carrier_id', table_name='carrier_vehicle')
    op.drop_table('carrier_vehicle')
    op.drop_table('admin_invite_token')
    op.drop_index('ix_carrier_company_telegram_user_id', table_name='carrier_company')
    op.drop_index('ix_carrier_company_status', table_name='carrier_company')
    op.drop_index('ix_carrier_company_paid_until', table_name='carrier_company')
    op.drop_table('carrier_company')
    # ### end Alembic commands ###
