"""add carrier profile step

Revision ID: 29229bd0d3ff
Revises: 0c5ce607aa08
Create Date: 2026-06-22 16:30:38.154444+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29229bd0d3ff'
down_revision: Union[str, None] = '0c5ce607aa08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_company', sa.Column('current_profile_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrier_company', 'current_profile_step')
    # ### end Alembic commands ###
