"""add job domain

Revision ID: b573a6ed3ed3
Revises: 29229bd0d3ff
Create Date: 2026-06-22 18:26:42.783235+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b573a6ed3ed3'
down_revision: Union[str, None] = '29229bd0d3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_assembly', sa.Boolean(), nullable=False),
    sa.Column('needs_packing', sa.Boolean(), nullable=False),
    sa.Column('needs_tail_lift', sa.Boolean(), nullable=False),
    sa.Column('needs_crane', sa.Boolean(), nullable=False),
    sa.Column('needs_mobile_lift', sa.Boolean(), nullable=False),
    sa.Column('required_loaders', sa.Integer(), nullable=True),
    sa.Column('estimated_payload_kg', sa.Integer(), nullable=True),
    sa.Column('estimated_volume_m3', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_client_telegram_user_id', 'job', ['client_telegram_user_id'], unique=False)
    op.create_index('ix_job_requested_date', 'job', ['requested_date'], unique=False)
    op.create_index('ix_job_status', 'job', ['status'], unique=False)
    op.create_table('job_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_address_city', 'job_address', ['city'], unique=False)
    op.create_index('ix_job_address_job_id', 'job_address', ['job_id'], unique=False)
    op.create_index('ix_job_address_kind', 'job_address', ['kind'], unique=False)
    op.create_table('job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('estimated_weight_kg', sa.Integer(), nullable=True),
    sa.Column('estimated_volume_m3', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_item_job_id', 'job_item', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_item_job_id', table_name='job_item')
    op.drop_table('job_item')
    op.drop_index('ix_job_address_kind', table_name='job_address')
    op.drop_index('ix_job_address_job_id', table_name='job_address')
    op.drop_index('ix_job_address_city', table_name='job_address')
    op.drop_table('job_address')
    op.drop_index('ix_job_status', table_name='job')
    op.drop_index('ix_job_requested_date', table_name='job')
    op.drop_index('ix_job_client_telegram_user_id', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
