"""add job offers

Revision ID: 9a35b8e7f183
Revises: b573a6ed3ed3
Create Date: 2026-06-22 18:56:26.778350+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a35b8e7f183'
down_revision: Union[str, None] = 'b573a6ed3ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carrier_note', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier_company.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['carrier_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_offer_carrier_id', 'job_offer', ['carrier_id'], unique=False)
    op.create_index('ix_job_offer_job_id', 'job_offer', ['job_id'], unique=False)
    op.create_index('ix_job_offer_status', 'job_offer', ['status'], unique=False)
    op.create_index('ix_job_offer_vehicle_id', 'job_offer', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_offer_vehicle_id', table_name='job_offer')
    op.drop_index('ix_job_offer_status', table_name='job_offer')
    op.drop_index('ix_job_offer_job_id', table_name='job_offer')
    op.drop_index('ix_job_offer_carrier_id', table_name='job_offer')
    op.drop_table('job_offer')
    # ### end Alembic commands ###
