"""add carrier profile fields

Revision ID: 0c5ce607aa08
Revises: 477a6175369c
Create Date: 2026-06-22 16:02:50.349038+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c5ce607aa08'
down_revision: Union[str, None] = '477a6175369c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_company', sa.Column('assembly_required', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carrier_company', sa.Column('packing_required', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carrier_company', sa.Column('operating_regions', sa.Text(), nullable=True))
    op.add_column('carrier_company', sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrier_company', 'profile_completed_at')
    op.drop_column('carrier_company', 'operating_regions')
    op.drop_column('carrier_company', 'packing_required')
    op.drop_column('carrier_company', 'assembly_required')
    # ### end Alembic commands ###
